import React from "react";
import contactPagePicture from "../../../static/assets/images/bio/emco.jpg";

export default function() {
    return (
        <div className="content-page-wrapper">
            <div
                className="left-column"
                style={{
                    background: "url(" + contactPagePicture + ") no-repeat",
                    backgroundSize: "cover",
                    backgroundPosition: "center"
                }}
            />
            <div className="right-column">
                <p>  Let's start off with telling you what I am, I'm a Hoosier! I was born and raised in Indianapolis Indiana to my loving parents Chris and Colleen. I have a 4 year older brother named Jamison.We have had many knock-out/drag-out fights over the years but we are still really close. He lives in Indianapolis still and I live in Venice Florida. My father lives here in Venice from September until May, "SnowBird". The other half of the year he lives in Northern Indiana on Lake Wawasee where my family has had cotteges since the 1920's.</p>
                <p>  I grew up going to the lake every weekend from Memorial day to Labor day where we race sailboats, waterski, swim, etc. I have a big extended family that goes to the lake as much as we do and we all get along great which is hard to do with 80+ of us consistently being together as much as we do. My Dad is one of 6 kids and our 4 cotteges are split up between us. After I graduated from Cathedral High School I went to play Soccer for Marian University. In my Junior year my house caught on fire and I was taken to the hospital where I was in a coma for 3 weeks due to smoke inhilation. It took me 6+ months to recover and when I did I didn't want my family thinking I would be crippled the rest of my life so I joined the US Army.</p>
                <p>In the Army I spent a year in South Korea then stationed to Fort Bragg North Carolina. At Bragg I was a part of the 82nd Airborne and deployed 3 times, a total of 39 months in combat in both Iraq and Afghanistan. After spending 8 years in the Army I didn't reinlist because of the many issues I received while being deployed such as back, hearing, PTSD, etc. I was a Transportation Manager with a secret security clearance and ran convoys distributing sensitive items such as Ammo, generators, and special individuals that needed extra security and secrecy. We were always targeted by the enemy because they knew the amount of security vehicles we rolled with for just a couple cargo trucks must be because the items we carried were very valuable.</p>
                <p>After I got out of the Army I got married and had the sweetest baby girl there is, Miss Emerson Colleen. I was living in Northern Indiana at my families lake house and was a special education teacher and soccer coach at Wawasee High School. I truely enjoyed living there because of the smalltown feel and relationships I had with the other teachers, students, and my soccer team all while having time to help my brother doing digital marketing and renovating my home. Ever since joining the military I rarely stayed in the same spot more than a year. I lived in many places in my life, many states and many countries, 18 countries to be exact. The countries I have been to for at least a week are the United States, Iraq, Afghanistan, Kuwait, Qutar, Kazakhstan, Turkey, Czech Republic, Germany, Austria, Italy, France, Belgium, Holland/Netherlands, British Virgin Islands, Canada, Japan, South Korea, and states like Indiana, Florida, North Carolina, Colorado, California, Nevada, Maryland, Virginia, and Ohio.</p> 
                <p>At the end of the fall semester I then moved here to Florida because my mother, Colleen, was sick and I wanted to be close to her and help out as much as I could. I was still working for my brother's company and could work anywhere and anytime making, monitoring, and updating our ads. I still work for him from time to time but I also am a charter fishing boat captain on my boat "Airnorne" and do commercial fishing trips with my captain on his boat catching Red Scamp Goliath and Gag Grouper, Red Lane and Vermilion Snapper, Blackfin Tuna, King and Spanish Mackerel, as well as others. When I do charters we only get the limit of what their license allows but when am commercial fishing we are out for 2-3 days and come home with 800-1000 pounds which is hundreds of fish all caught from a rod and reel. With time to spare between fishing trips I began going back to school for my full-stack development certificate that will help alongside my bachelors degree in Computer Information Technology from Campbell University. That is me in a nutshell, people always tell me I should do a full biography because how interesting my life has been up to this point but that can be done at a later date.</p>

            </div>
        </div>
    );
}